OPENCV_VERSION := 3


INCLUDE_DIRS := /usr/local/include /home/ubuntu/packages/OpenBLAS/build/include
LIBRARY_DIRS := /usr/local/lib /home/ubuntu/packages/OpenBLAS/build/lib /usr/lib/x86_64-linux-gnu

# build dir
BUILD_DIR := build

LIBRARIES := opencv_core opencv_highgui opencv_imgproc opencv_saliency opencv_objdetect openblas
